name: Generate Java Docs 
on: [push]
permissions: 
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Format Code
        run: ./scripts/format.sh 
      - name: Compile and Test with Maven 
        run: ./scripts/package_verify.sh 